services:
  scib:
    build: 
      context: scib
    image: bigdatainbiomedicine/sc-scib:1.0
  rpy:
    build: 
      context: rpy
    image: bigdatainbiomedicine/sc-rpy:1.0
  rapids:
    build: 
      context: rapids
    image: bigdatainbiomedicine/sc-rapids:0.1
