name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest

    steps:
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        run: cd example && ./run.sh